<a href="https://colab.research.google.com/github/Whaleman0423/-Python-book-practice/blob/main/tfKs_ch0_numpy20211016%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#tf.Keras numpy快速上手，自我練習


## 0-0

#### shape 有幾個數 => 即 幾 軸 (或 幾階)
#### 例如 [[1, 2, 3] , [4, 5, 6]]  => shape => (2, 3) => 兩軸
#### => 第 0 軸 => 2維
#### => 第 1 軸 => 3維

### 單軸 => 向量 
### 例如: [1, 2, 3, 4] => shape => (4,) => (單軸)四維向量

#### 雙軸 => 矩陣
#### 例如:[[1, 2, 3, 4], [5, 6, 7, 8]] => shape => (2, 4) => (雙軸) 2 ×　4 矩陣 
#### 第一軸是 => 2維 ， 第二軸是 => 四維
 

### 3D 向量 vs. 3D 陣列 :
### 3D 向量 => 單軸 => shape => (3,) => 例子: [1, 2, 3]
### 3D 陣列 => 三軸 => 例子 => shape => (1, 2, 3) => 第一軸是 => 1維 ， 第二軸是 => 2維 ， 第三軸是 => 3維

# 此書 D 皆代表 "軸"

## Numpy 的 優點:
### 1. 占空間小，存取速度快
### 2. 所有元素的型別的必須相同
### 3. 每軸的元素數 必須和shape相同
#### 如 2　×　2 陣列 不能是 [[1, 2], [3]] 或 [[1, 2], [3, 4, 5]]

## 0-1

In [2]:
import numpy as np  # 匯入Numpy 套件

##### 建立一個形狀為(3, 5, 2) 且 元素均為 0 的陣列

In [5]:
x = np.zeros((3, 5, 2)) 

##### 顯示 軸數屬性

In [6]:
x.ndim

3

##### 顯示形狀屬性

In [7]:
x.shape

(3, 5, 2)

##### 顯示型別屬性

In [8]:
x.dtype

dtype('float64')

##### 0D => 純量 ex: 5

In [12]:
x = np.zeros(5)
y = x.astype("uint8") # 轉出為 unit8 並指定給 y 變數
print(y.dtype)
print(x.dtype)

uint8
float64


##0-2

In [13]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [15]:
x = np.zeros((2, 3, 2))
x

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
x = np.zeros(2, dtype="uint8")
x

array([0, 0], dtype=uint8)

In [21]:
x = np.ones((2, 3))
print(x.dtype)
x

float64


array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
x = np.ones((2, 3), dtype="uint8")
x

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [25]:
x = np.full((2, 3), 7)
x

array([[7, 7, 7],
       [7, 7, 7]])

#####用np.arrange建立類似range()的陣列

In [27]:
x = np.arange(5)


array([0, 1, 2, 3, 4])

##### 用 copy() 來複製一份

In [28]:
y = np.copy(x)
y

array([0, 1, 2, 3, 4])

In [30]:
y = np.zeros_like(x)
y

array([0, 0, 0, 0, 0])

In [31]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

##0-3

##### array[清單] =>取出值

In [32]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x[1, 2]

6

##### 也可以寫成

In [33]:
x[1][2]

6

In [34]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [35]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x[::2, 2:0:-1]

array([[3, 2],
       [9, 8]])

In [36]:
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

## 0-4